version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: irasshaimasedb
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - MYSQL_USER=sunny
      - MYSQL_PASSWORD=tiger
      - MYSQL_DATABASE=irasshaimase
      - TZ=UTC

    volumes:
      - ./src/main/resources/db/migration/V1__init.sql:/docker-entrypoint-initdb.d/V1__init.sql
      - irasshaimasedb:/var/lib/mysql

volumes:
  irasshaimasedb:
